services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: erp_user
      POSTGRES_PASSWORD: erp_pass
      POSTGRES_DB: erp_db
    ports:
      - "5432:5432"
  redis:
    image: redis
    ports:
      - "6379:6379"